spring:
  datasource:
    url: jdbc:mysql://yogit.cgkajadrhiod.ap-northeast-2.rds.amazonaws.com/yogit_db
    username: yogit
    password: dyrlt!12
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create